/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senactech.sistemaRH.view;

import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author Marcia
 */
public class GUIMenu extends javax.swing.JInternalFrame implements InternalFrameListener {
   private boolean flagQuadroLotacao = true;
   

    
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jdpmenu = new javax.swing.JDesktopPane();
        jbqla = new javax.swing.JButton();
        jlbtitulomenu = new javax.swing.JLabel();
        jlbltitulomenu2 = new javax.swing.JLabel();
        jbturnover = new javax.swing.JButton();
        jbhoraextra = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jButton1.setText("jButton1");

        setClosable(true);
        setMaximizable(true);

        jdpmenu.setBackground(new java.awt.Color(153, 255, 153));

        jbqla.setText("Quadro de Lotação");
        jbqla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbqlaActionPerformed(evt);
            }
        });

        jlbtitulomenu.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jlbtitulomenu.setText("MENU");

        jlbltitulomenu2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jlbltitulomenu2.setText("Escolha uma opção:");

        jbturnover.setText("TurnOver");
        jbturnover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbturnoverActionPerformed(evt);
            }
        });

        jbhoraextra.setText("Hora Extra");
        jbhoraextra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhoraextraActionPerformed(evt);
            }
        });

        jdpmenu.setLayer(jbqla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenu.setLayer(jlbtitulomenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenu.setLayer(jlbltitulomenu2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenu.setLayer(jbturnover, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenu.setLayer(jbhoraextra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpmenuLayout = new javax.swing.GroupLayout(jdpmenu);
        jdpmenu.setLayout(jdpmenuLayout);
        jdpmenuLayout.setHorizontalGroup(
            jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpmenuLayout.createSequentialGroup()
                .addGroup(jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpmenuLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jlbtitulomenu))
                    .addGroup(jdpmenuLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpmenuLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jbqla))
                            .addComponent(jlbltitulomenu2)))
                    .addGroup(jdpmenuLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbhoraextra)
                            .addComponent(jbturnover))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jdpmenuLayout.setVerticalGroup(
            jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbtitulomenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbltitulomenu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbqla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbturnover)
                .addGap(18, 18, 18)
                .addComponent(jbhoraextra)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpmenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpmenu))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbqlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbqlaActionPerformed
          GUIQuadrodeLotacao ql = new GUIQuadrodeLotacao();
            GUIPrincipal.jdpPrincipal.add(ql);
            ql.setVisible(true);
        
    }//GEN-LAST:event_jbqlaActionPerformed

    private void jbturnoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbturnoverActionPerformed
        GUITurnover to = new GUITurnover();
            GUIPrincipal.jdpPrincipal.add(to);
            to.setVisible(true);
    }//GEN-LAST:event_jbturnoverActionPerformed

    private void jbhoraextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhoraextraActionPerformed
        GUIHe he = new GUIHe();
            GUIPrincipal.jdpPrincipal.add(he);
            he.setVisible(true);
    }//GEN-LAST:event_jbhoraextraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton jbhoraextra;
    private javax.swing.JButton jbqla;
    private javax.swing.JButton jbturnover;
    public static javax.swing.JDesktopPane jdpmenu;
    private javax.swing.JLabel jlbltitulomenu2;
    private javax.swing.JLabel jlbtitulomenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
